export const images = {
    logo: require('../assets/images/logo.png'),
    logo_white: require('../assets/images/logo_white.png'),
    certificated: require('../assets/images/certificated.png'),
    vitepay_logo: require('../assets/images/vitepay_logo.png'),
    avant: require('../assets/images/avant.png'),
    arriere: require('../assets/images/arriere.jpg'),
    alimentation: require('../assets/images/alimentation.jpg'),
    electronique: require('../assets/images/electronique.jpg'),
    fashion: require('../assets/images/fashion.jpg'),
    restauration: require('../assets/images/restauration.jpg'),
    supermarche: require('../assets/images/supermarche.jpg'),
    erease_filter: require('../assets/images/erease_filter.png'),
    fleche_haut: require('../assets/images/fleche_haut.png'),
    fleche_bas: require('../assets/images/fleche_bas.png'),

}

export const colors = {
    main: '#E91E63',
    main_black: '#001E37',

    bg_color: '#F7F7F7',
    white: '#FFFFFF',
    black: '#000000',
    tomato: '#FF5851',
    light_gray: '#AFAFAF',
    facebook_color: '#077AE9',
    instagram_color: '#DC4D5A',
    linkedin_color: '#0274B3',

    success: '#00CC8D',
    error: '#e23636',
    warning: '#edb95e',
}

export const categories = [
    { id: '1', name: 'Alimentation' },
    { id: '2', name: 'Fashion' },
    { id: '3', name: 'Cosmétique' },
    { id: '4', name: 'Hôtel/Auberge' },
    { id: '5', name: 'Électronique' },
    { id: '6', name: 'Billeterie' },
    { id: '7', name: 'Immobilier/Déco' },
    { id: '8', name: 'Jeu' },
    { id: '9', name: 'Sport' },
    { id: '10', name: 'Supermarché' },
    { id: '11', name: 'Restaurations' },
    { id: '12', name: 'Médecine' },
    { id: '13', name: 'Quincaillerie' },
    { id: '14', name: 'Véhicule' },
    { id: '15', name: 'Itech' },
    { id: '16', name: 'Musique' },
    { id: '17', name: 'Elearning' },
    { id: '18', name: 'Agriculture' },
    { id: '19', name: 'Expédition' },
    { id: '20', name: 'Mode Femme' },
    { id: '21', name: 'Mode Homme' },
    { id: '22', name: 'Bijoux et montres' },
    { id: '23', name: 'Sacs et Chaussures' },
    { id: '24', name: 'Jouets et Enfants' },
    { id: '25', name: 'Beauté, santé et cheveux' },
    { id: '26', name: 'Autos et Motos' },
    { id: '27', name: 'Outils et bricolage' },
]